---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install xorg
  apt:
    name: xorg
    state: present
  
- name: Install LXDE Core
  apt:
    name: lxde-core
    state: present

- name: Install Firefox
  apt:
    name: firefox
    state: present

- name: Install Archive Manager
  apt:
    name: file-roller
    state: present